In [1]:
import pandas as pd
import numpy as np 
from numpy import genfromtxt
import scipy.stats as stats




In [11]:
a = [[-8, -8, -8], [-7, -15, -9], [-7, -8, -9],[-9, -8, -9],[-7, -3, -9],[-9, -7, -9],[-6, -9, -10]]
z = np.abs(stats.zscore(a,axis=0))
print(z)

print(np.where(z>1.5))
outlier = (z < 1.5).all(axis=1)

result = [x for x, y in zip(a, outlier) if y == True]

print(outlier)
print(result)

b = [-8,-7,-7,-9,-7]
print(np.std(b))

# b = np.array(a)
# b = np.mean(a,axis = 0)
# print(b)

[[0.40824829 0.08703883 1.87082869]
 [0.54433105 2.04541246 0.        ]
 [0.54433105 0.08703883 0.        ]
 [1.36082763 0.08703883 0.        ]
 [0.54433105 1.61021832 0.        ]
 [1.36082763 0.39167473 0.        ]
 [1.4969104  0.21759707 1.87082869]]
(array([0, 1, 4, 6]), array([2, 1, 1, 2]))
[False False  True  True False  True False]
[[-7, -8, -9], [-9, -8, -9], [-9, -7, -9]]
0.8


In [30]:
a = [[-8, -8, -8], [-7, -15, -9], [-7, -8, -9],[-9, -8, -9],[-7, -3, -9],[-9, -7, -9],[-6, -9, -10]]
Q1 = np.quantile(a, .25,axis=0)
Q2 = np.quantile(a, .75,axis=0)
print("Q2 quantile of arr : ",Q1 )
print("Q2 quantile of arr : ", Q2)
IQR = Q2 -Q1
print(IQR)

b =~((a < (Q1 - 1.5 * IQR)) |(a > (Q2+ 1.5 * IQR)))
outlier = [ True if all(l) else False for l in b  ]
result = [x for x, y in zip(a, outlier) if y == True]
print(outlier)
print(b)


Q2 quantile of arr :  [-8.5 -8.5 -9. ]
Q2 quantile of arr :  [-7.  -7.5 -9. ]
[1.5 1.  0. ]
[False, False, True, True, False, True, False]
[[ True  True False]
 [ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True  True False]]


In [68]:
f = "/home/kepler42/EE494/EE494/merged.csv"
df = pd.read_csv(f,sep=',')
print(df)

      Unnamed: 0      0    1   2   3   4
0              0    0.0  500 -41 -45 -55
1              1    0.0  500 -41 -45 -57
2              2    0.0  500 -41 -43 -55
3              3    0.0  500 -45 -43 -57
4              4    0.0  500 -45 -43 -55
...          ...    ...  ...  ..  ..  ..
5745        5745  327.0  731 -41 -47 -45
5746        5746  327.0  731 -41 -47 -45
5747        5747  327.0  731 -41 -45 -45
5748        5748  327.0  731 -39 -45 -47
5749        5749  327.0  731 -41 -47 -45

[5750 rows x 6 columns]


In [49]:
x_y = np.asarray(df[['0','1']] )

feature_cols = df.columns.to_list()

feature_cols.remove('Unnamed: 0')
x = np.asarray(df[feature_cols])

In [51]:
dim = np.zeros((x_y.shape[0],x_y.shape[1]+1))
dim[:,:-1] = y

In [52]:
dim

array([[  0., 500.,   0.],
       [  0., 500.,   0.],
       [  0., 500.,   0.],
       ...,
       [327., 731.,   0.],
       [327., 731.,   0.],
       [327., 731.,   0.]])