In [30]:
import pandas as pd
import numpy as np 
from numpy import genfromtxt
import scipy.stats as stats




In [69]:
a = [[-8, -8, -8], [-7, -888, -9], [-7, -8, -9]]
z = np.abs(stats.zscore(a,axis=0))
print(z)

print(np.where(z>1.5))
outlier = (z < 1.5).all(axis=1)

result = [x for x, y in zip(a, outlier) if y == True]

print(new)
print(result)

# b = [7, 4, 1, 75]
# print(np.std(b))

# b = np.array(a)
# b = np.mean(a,axis = 0)
# print(b)

[[1.41421356 0.70710678 1.41421356]
 [0.70710678 1.41421356 0.70710678]
 [0.70710678 0.70710678 0.70710678]]
(array([], dtype=int64), array([], dtype=int64))
[ True  True False False]
[[-8, -8, -8], [-7, -888, -9], [-7, -8, -9]]


In [68]:
f = "/home/kepler42/EE494/EE494/merged.csv"
df = pd.read_csv(f,sep=',')
print(df)

      Unnamed: 0      0    1   2   3   4
0              0    0.0  500 -41 -45 -55
1              1    0.0  500 -41 -45 -57
2              2    0.0  500 -41 -43 -55
3              3    0.0  500 -45 -43 -57
4              4    0.0  500 -45 -43 -55
...          ...    ...  ...  ..  ..  ..
5745        5745  327.0  731 -41 -47 -45
5746        5746  327.0  731 -41 -47 -45
5747        5747  327.0  731 -41 -45 -45
5748        5748  327.0  731 -39 -45 -47
5749        5749  327.0  731 -41 -47 -45

[5750 rows x 6 columns]


In [49]:
x_y = np.asarray(df[['0','1']] )

feature_cols = df.columns.to_list()

feature_cols.remove('Unnamed: 0')
x = np.asarray(df[feature_cols])

In [51]:
dim = np.zeros((x_y.shape[0],x_y.shape[1]+1))
dim[:,:-1] = y

In [52]:
dim

array([[  0., 500.,   0.],
       [  0., 500.,   0.],
       [  0., 500.,   0.],
       ...,
       [327., 731.,   0.],
       [327., 731.,   0.],
       [327., 731.,   0.]])