In [1]:
import pandas as pd
import numpy as np 
from numpy import genfromtxt
import scipy.stats as stats

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split


import numpy as np
import pandas as pd
from numpy import genfromtxt
from sklearn.cluster import KMeans, AffinityPropagation, SpectralClustering
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
import time

from sklearn.metrics import r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.multioutput import MultiOutputRegressor

from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


from sklearn.metrics import explained_variance_score
from sklearn.metrics import hamming_loss
from sklearn.metrics import max_error

from sklearn.metrics import mean_absolute_percentage_error

import os, glob



In [48]:
def z_score(data_points):
    z_score = np.abs(stats.zscore(data_points,axis=0,nan_policy='omit'))
    print(z_score)

    outlier = (z_score < 1.6).all(axis=1) 

    return [x for x, y in zip(data_points, outlier) if y == True]

a = [[12, 15, 13], [12, 15, 14],[14, 15, 16]]

z_score(a)

#mean_point = np.mean(result,axis = 0) if (len(result) !=0) else np.mean(a,axis = 0)



[[0.70710678        nan 1.06904497]
 [0.70710678        nan 0.26726124]
 [1.41421356        nan 1.33630621]]


[]

In [4]:
def IQR(data_points):
    Q1 = np.quantile(data_points, .25,axis=0)
    Q2 = np.quantile(data_points, .75,axis=0)

    IQR = Q2 -Q1
    b =~((data_points < (Q1 - 1.5 * IQR)) |(data_points > (Q2+ 1.5 * IQR)))
    outlier = [ True if all(l) else False for l in b  ]
    return [x for x, y in zip(a, outlier) if y == True]


In [31]:
a = [[-8, -8, -8], [-7, -15, -9], [-7, -8, -9],[-9, -8, -9],[-7, -3, -9],[-9, -7, -9],[-6, -9, -10]]

result = IQR



print(outlier)
print(b)
print(result)


Q2 quantile of arr :  [-8.5 -8.5 -9. ]
Q2 quantile of arr :  [-7.  -7.5 -9. ]
[1.5 1.  0. ]
[False, False, True, True, False, True, False]
[[ True  True False]
 [ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]
 [ True  True False]]
[[-7, -8, -9], [-9, -8, -9], [-9, -7, -9]]


In [5]:
a = [[-8, -8, -8], [-7, -15, -9], [-7, -8, -9],[-9, -8, -9],[-7, -3, -9],[-9, -7, -9],[-6, -9, -10]]
print(IQR(a))

[[-7, -8, -9], [-9, -8, -9], [-9, -7, -9]]


In [68]:
f = "/home/kepler42/EE494/EE494/merged.csv"
df = pd.read_csv(f,sep=',')
print(df)

      Unnamed: 0      0    1   2   3   4
0              0    0.0  500 -41 -45 -55
1              1    0.0  500 -41 -45 -57
2              2    0.0  500 -41 -43 -55
3              3    0.0  500 -45 -43 -57
4              4    0.0  500 -45 -43 -55
...          ...    ...  ...  ..  ..  ..
5745        5745  327.0  731 -41 -47 -45
5746        5746  327.0  731 -41 -47 -45
5747        5747  327.0  731 -41 -45 -45
5748        5748  327.0  731 -39 -45 -47
5749        5749  327.0  731 -41 -47 -45

[5750 rows x 6 columns]


In [49]:
x_y = np.asarray(df[['0','1']] )

feature_cols = df.columns.to_list()

feature_cols.remove('Unnamed: 0')
x = np.asarray(df[feature_cols])

In [51]:
dim = np.zeros((x_y.shape[0],x_y.shape[1]+1))
dim[:,:-1] = y

In [52]:
dim

array([[  0., 500.,   0.],
       [  0., 500.,   0.],
       [  0., 500.,   0.],
       ...,
       [327., 731.,   0.],
       [327., 731.,   0.],
       [327., 731.,   0.]])

In [5]:


path_to_data = "/home/kepler42/EE494/EE494/Cluster/merged2.csv"
df = pd.read_csv(path_to_data,sep=',')

feature_cols = df.columns.to_list()
rem = ['Unnamed: 0','0','1','x_y']
keep = ['2','3','4']

x = np.asarray(df[keep])
print(x)

#x_y coordinates target vars
x_y = np.asarray(df[['0','1']] )



    


[[-47 -45 -53]
 [-47 -45 -51]
 [-47 -45 -51]
 ...
 [-47 -49 -41]
 [-47 -47 -43]
 [-47 -45 -41]]
[[  0. 500.]
 [  0. 500.]
 [  0. 500.]
 ...
 [327. 731.]
 [327. 731.]
 [327. 731.]]


In [23]:
method = 'knnC'

if method=='knnC':
    df["x_y"] = (df["0"].apply(str) +";"+ df["1"].apply(str)).astype("string")
    x_y = np.asarray(df[['x_y']] )

    

x = np.asarray(df[keep])
X_train, X_test, y_train, y_test = train_test_split(x, x_y, test_size=0.20, shuffle=True)




[[-45 -43 -49]
 [-39 -45 -47]
 [-41 -47 -49]
 ...
 [-35 -53 -45]
 [-51 -47 -17]
 [-39 -45 -45]] [[-45 -45 -41]
 [-49 -41 -53]
 [-39 -47 -47]
 ...
 [-49 -43 -41]
 [-47 -47 -49]
 [-55 -43 -39]]


In [13]:
class MultiColumnLabelEncoder:

    def __init__(self, columns=None):
        self.columns = columns # array of column names to encode


    def fit(self, X, y=None):
        self.encoders = {}
        columns = X.columns if self.columns is None else self.columns
        for col in columns:
            self.encoders[col] = LabelEncoder().fit(X[col])
        return self


    def transform(self, X):
        output = X.copy()
        columns = X.columns if self.columns is None else self.columns
        for col in columns:
            output[col] = self.encoders[col].transform(X[col])
        return output


    def fit_transform(self, X, y=None):
        return self.fit(X,y).transform(X)


    def inverse_transform(self, X):
        output = X.copy()
        columns = X.columns if self.columns is None else self.columns
        for col in columns:
            output[col] = self.encoders[col].inverse_transform(X[col])
        return output

In [16]:
multi = MultiColumnLabelEncoder(columns=['x_y'])
df = multi.fit_transform(df)
df.head()

Unnamed: 0    0    1   2   3   4  x_y
0           0  0.0  500 -47 -45 -53    4
1           1  0.0  500 -47 -45 -51    4
2           2  0.0  500 -47 -45 -51    4
3           3  0.0  500 -47 -45 -51    4
4           4  0.0  500 -47 -45 -51    4

In [17]:
inv = multi.inverse_transform(df)
inv.head()

Unnamed: 0    0    1   2   3   4      x_y
0           0  0.0  500 -47 -45 -53  0.0;500
1           1  0.0  500 -47 -45 -51  0.0;500
2           2  0.0  500 -47 -45 -51  0.0;500
3           3  0.0  500 -47 -45 -51  0.0;500
4           4  0.0  500 -47 -45 -51  0.0;500

In [52]:
knn = KNeighborsClassifier(n_neighbors = 8, weights='uniform', algorithm='auto')
regr = MultiOutputClassifier(knn)
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)

In [83]:
def str_to_xy(pred):
    pred = pred.flatten()
    
    return np.array([list(map(float,x_y.split(';'))) for x_y in pred])

In [84]:
# print(y_pred)


#print(y_pred)
q = str_to_xy(y_pred)
print(q)





[[327.  731. ]
 [250.5 375. ]
 [ 90.  250. ]
 [  0.  375. ]
 [200.5 250. ]
 [200.5 250. ]
 [  0.  250. ]
 [ 90.  375. ]
 [ 90.  731. ]
 [  0.  250. ]
 [250.5 375. ]
 [200.5 375. ]
 [ 90.  625. ]
 [327.  731. ]
 [200.5 375. ]
 [  0.  375. ]
 [ 90.  125. ]
 [250.5 375. ]
 [157.5   0. ]
 [ 90.  250. ]
 [  0.    0. ]
 [ 90.  625. ]
 [  0.  375. ]
 [  0.  125. ]
 [ 90.  625. ]
 [ 90.  125. ]
 [327.  731. ]
 [ 90.  375. ]
 [  0.  375. ]
 [  0.  250. ]
 [  0.  375. ]
 [157.5   0. ]
 [157.5   0. ]
 [200.5 500. ]
 [ 90.  250. ]
 [ 90.  625. ]
 [157.5   0. ]
 [ 90.  625. ]
 [200.5 250. ]
 [ 90.  731. ]
 [284.  500. ]
 [ 90.  731. ]
 [200.5 500. ]
 [200.5 500. ]
 [316.6 625. ]
 [157.5   0. ]
 [ 90.  125. ]
 [ 90.  731. ]
 [ 90.    0. ]
 [200.5 250. ]
 [ 90.  250. ]
 [ 90.  250. ]
 [200.5 250. ]
 [200.5 731. ]
 [200.5 500. ]
 [187.1 125. ]
 [327.  731. ]
 [327.  731. ]
 [  0.  500. ]
 [200.5 250. ]
 [187.1 125. ]
 [200.5 250. ]
 [187.1 125. ]
 [ 90.  731. ]
 [  0.    0. ]
 [ 90.    0. ]
 [157.5   